# Site settings
title: TheGreighCanary
description: Testing
baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: TheGreighCanary
user_description: Testing
user_title: Freelane Web Designer
email: greighcanary@icloud.com
twitter_username: thegreighcanary
github_username:  greigh
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
